Imports System.IO
Imports System.Threading
Imports System.Configuration

Imports HSPBOTBroadcast.BOT
Public Class Form1

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim X As New Plugin_ADStar(Nothing)
        X._Create()
        'X.Execute()
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        'Dim DaftarUser As New GetAgeover10days(ActiveSession)
        'Dim DataSet As DataSet = DaftarUser.GetAge()

        'Dim DaftarUmurUser As New GetAgeover10days(ActiveSession)
        'Dim DTUmur As DataTable = DaftarUmurUser.GetAge().Tables("View")
        'Dim Message = "=========================" + vbCrLf +
        '                "[NoReplay] Info Stock Sparepart [NoReplay]" + vbCrLf +
        '                "=========================" + vbCrLf +
        '                "PERHATIAN!!!" + vbCrLf +
        '                "Umur Stock Sparepart anda sudah mendekati 2 minggu setelah pengambilan terakhir. " + vbCrLf +
        '                "Silahkan Melakukan refreshment atau Retur ke Gudang Sparepart dan melakukan Bon Sparepart lagi" + vbCrLf +
        '                vbCrLf + vbCrLf + "=========================" + vbCrLf +
        '                "This Message Generated by Telegram Bot Server"

        'If (DTUmur.Rows.Count > 0) Then
        '    For Each RowSet As DataRow In DTUmur.Rows
        '        If (RowSet("UserIDTelegram") <> "") Then
        '            Console.WriteLine(Message)
        '        End If
        '    Next
        'End If
    End Sub
    Private Schedular As Timer
    Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
        Dim Var_Seting As New GetSetting(ActiveSession)
        Dim dataset As DataSet = Var_Seting.GetSetting_BC()
        Console.WriteLine(TimeOfDay.ToString("hh:mm:ss"))
        For Each DR As DataRow In dataset.Tables(0).Rows
            If TimeOfDay.ToString("hh:mm:tt") = DR("time").ToString Then
                Console.WriteLine("excec")
            Else
                Console.WriteLine("Kurang")
            End If
        Next
        'Dim xx As New SrvBroadcast
        'xx.ScheduleService("08:00:00", "MKT", "667213449", "DAILY")
        'Try
        '    'Schedular = New Timer(New TimerCallback(AddressOf SchedularCallback))
        '    Dim mode As String = My.Settings.Mode.ToUpper()
        '    Dim Var_Seting As New GetSetting(ActiveSession)
        '    'Set the Default Time.
        '    Dim scheduledTime As DateTime = DateTime.MinValue

        '    Dim dataset As DataSet = Var_Seting.GetSetting_BC()

        '    For Each DR As DataRow In dataset.Tables(0).Rows

        '        If (DR("intervalset") = "DAILY") Then
        '            'Get the Scheduled Time from AppSettings.
        '            scheduledTime = DateTime.Parse(DR("time").ToString())
        '            If DateTime.Now > scheduledTime Then
        '                'If Scheduled Time is passed set Schedule for the next day.
        '                scheduledTime = scheduledTime.AddDays(1)
        '            End If
        '        End If
        '        If (DR("intervalset").ToUpper() = "INTERVAL") Then
        '            'Get the Interval in Minutes from AppSettings.
        '            Dim intervalMinutes As Integer = Convert.ToInt32(DR("time").ToString())

        '            'Set the Scheduled Time by adding the Interval to Current Time.
        '            scheduledTime = DateTime.Now.AddMinutes(intervalMinutes)
        '            If DateTime.Now > scheduledTime Then
        '                'If Scheduled Time is passed set Schedule for the next Interval.
        '                scheduledTime = scheduledTime.AddMinutes(intervalMinutes)
        '            End If
        '        End If

        '        Dim timeSpan As TimeSpan = scheduledTime.Subtract(DateTime.Now)
        '        Dim schedule As String = String.Format("{0} day(s) {1} hour(s) {2} minute(s) {3} seconds(s)", timeSpan.Days, timeSpan.Hours, timeSpan.Minutes, timeSpan.Seconds)
        '        If DR("rolename") = "MKT" Then 'Marketing
        '            Me.SendBroadcast(DR("userid"))
        '        ElseIf DR("rolename") = "PTG" Then 'Piutang
        '            Me.SendBroadcast_PTG(DR("userid"))
        '        ElseIf DR("rolename") = "PIC" Then 'PPIC
        '            Me.SendBroadcast_PIC(DR("userid"))
        '        ElseIf DR("rolename") = "SPR" Then 'Sparepart
        '            Me.SendBroadcast_SPR(DR("userid"))
        '        End If
        '        'Get the difference in Minutes between the Scheduled and Current Time.
        '        'Dim dueTime As Integer = Convert.ToInt32(timeSpan.TotalMilliseconds)

        '        'Change the Timer's Due Time.
        '        'Schedular.Change(dueTime, Timeout.Infinite)
        '    Next
        'Catch ex As Exception

        '    Console.WriteLine("Simple Service Error on: {0} " + ex.Message + ex.StackTrace)

        '    'Stop the Windows Service.
        '    'Using serviceController As New System.ServiceProcess.ServiceController("SimpleService")
        '    '    serviceController.[Stop]()
        '    'End Using
        'End Try
    End Sub

End Class