Imports Dapper
Namespace HSP.Data
    Public Class BroadcastCore
        Private _DBConnection As DBConnection
        Sub New(ByVal Session As Object)
            _DBConnection = New DBConnection(Session)
        End Sub

        Public Function Broadcast_Start(ByVal subject As String, ByVal Filename As String, ByVal Body As String, ByVal _ext As String) As Integer
            Dim SQL As String
            Dim Title As String = "=========================" + vbCrLf +
                                    "[NoReplay] " + subject.ToUpper + "[NoReplay] " +
                                    "========================="
            Dim Footer As String = vbCrLf + vbCrLf + "=========================" + vbCrLf +
                                    "This Message Generated by Telegram Bot Server"
            If (Filename = "") Then
                SQL = "insert into outbox " +
                    "select (select MAX(UpdateID)+1 from outbox) test, UserID " +
                    " ,'" + Title + "" + vbCrLf + vbCrLf +
                    "" + Body + Footer + "',now(),0,'',0 from user where active = 1"
            Else
                SQL = "insert into outbox " +
                    "select (select MAX(UpdateID)+1 from outbox) test, UserID " +
                    " ,'" + Title + "" + vbCrLf + vbCrLf +
                    "" + Body + Footer + "',now(),case when substr('" + _ext + "',2,4) = 'PDF' then 1 when substr('" + _ext + "',2,4) in('JPG','PNG','GIF','JPEG') then 2 else 0 end,'" + Filename + "',0 from user where active = 1"
            End If
            Using DBX As IDbConnection = _DBConnection.Connection
                Broadcast_Start = DBX.Execute(SQL)
            End Using
        End Function
        Public Function ShowData() As DataSet
            Dim SQL As String
            SQL = "Select UpdateID,CONVERT(ChatTime,date) TglKirim,ChatText, FileName attachment,COUNT(ChatID) TotalTerkirim from outbox where ChatTime is not null and left(Chattext,1) = '=' group by UpdateID"

            Using DBX As IDbConnection = _DBConnection.Connection()
                Dim CMD As New MySql.Data.MySqlClient.MySqlCommand(SQL, DBX)
                Dim DA As New MySql.Data.MySqlClient.MySqlDataAdapter
                Dim DS As New DataSet

                DA.SelectCommand = CMD
                DA.Fill(DS, "View")

                ShowData = DS
            End Using
        End Function

        Public Function Resend(ByVal ID As String) As Integer
            Dim Sql As String
            Sql = "Update Outbox set Chattime = now(),status = 0 where updateid = '" + ID + "'"
            Using DBX As IDbConnection = _DBConnection.Connection()
                Resend = DBX.Execute(Sql)
            End Using
        End Function
    End Class
End Namespace
